// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_gateway.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5fgateway_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_client_5fgateway_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_client_5fgateway_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5fgateway_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_client_5fgateway_2eproto;
namespace game {
namespace client {
class ClientChatPush;
struct ClientChatPushDefaultTypeInternal;
extern ClientChatPushDefaultTypeInternal _ClientChatPush_default_instance_;
class ClientChatRequest;
struct ClientChatRequestDefaultTypeInternal;
extern ClientChatRequestDefaultTypeInternal _ClientChatRequest_default_instance_;
class ClientChatResponse;
struct ClientChatResponseDefaultTypeInternal;
extern ClientChatResponseDefaultTypeInternal _ClientChatResponse_default_instance_;
class ClientJoinMatchRequest;
struct ClientJoinMatchRequestDefaultTypeInternal;
extern ClientJoinMatchRequestDefaultTypeInternal _ClientJoinMatchRequest_default_instance_;
class ClientJoinMatchResponse;
struct ClientJoinMatchResponseDefaultTypeInternal;
extern ClientJoinMatchResponseDefaultTypeInternal _ClientJoinMatchResponse_default_instance_;
class ClientLoginRequest;
struct ClientLoginRequestDefaultTypeInternal;
extern ClientLoginRequestDefaultTypeInternal _ClientLoginRequest_default_instance_;
class ClientLoginResponse;
struct ClientLoginResponseDefaultTypeInternal;
extern ClientLoginResponseDefaultTypeInternal _ClientLoginResponse_default_instance_;
class ClientMatchSuccessPush;
struct ClientMatchSuccessPushDefaultTypeInternal;
extern ClientMatchSuccessPushDefaultTypeInternal _ClientMatchSuccessPush_default_instance_;
}  // namespace client
}  // namespace game
PROTOBUF_NAMESPACE_OPEN
template<> ::game::client::ClientChatPush* Arena::CreateMaybeMessage<::game::client::ClientChatPush>(Arena*);
template<> ::game::client::ClientChatRequest* Arena::CreateMaybeMessage<::game::client::ClientChatRequest>(Arena*);
template<> ::game::client::ClientChatResponse* Arena::CreateMaybeMessage<::game::client::ClientChatResponse>(Arena*);
template<> ::game::client::ClientJoinMatchRequest* Arena::CreateMaybeMessage<::game::client::ClientJoinMatchRequest>(Arena*);
template<> ::game::client::ClientJoinMatchResponse* Arena::CreateMaybeMessage<::game::client::ClientJoinMatchResponse>(Arena*);
template<> ::game::client::ClientLoginRequest* Arena::CreateMaybeMessage<::game::client::ClientLoginRequest>(Arena*);
template<> ::game::client::ClientLoginResponse* Arena::CreateMaybeMessage<::game::client::ClientLoginResponse>(Arena*);
template<> ::game::client::ClientMatchSuccessPush* Arena::CreateMaybeMessage<::game::client::ClientMatchSuccessPush>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace game {
namespace client {

// ===================================================================

class ClientLoginRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.client.ClientLoginRequest) */ {
 public:
  inline ClientLoginRequest() : ClientLoginRequest(nullptr) {}
  ~ClientLoginRequest() override;
  explicit constexpr ClientLoginRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientLoginRequest(const ClientLoginRequest& from);
  ClientLoginRequest(ClientLoginRequest&& from) noexcept
    : ClientLoginRequest() {
    *this = ::std::move(from);
  }

  inline ClientLoginRequest& operator=(const ClientLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientLoginRequest& operator=(ClientLoginRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientLoginRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientLoginRequest* internal_default_instance() {
    return reinterpret_cast<const ClientLoginRequest*>(
               &_ClientLoginRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientLoginRequest& a, ClientLoginRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientLoginRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientLoginRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientLoginRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientLoginRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientLoginRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientLoginRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientLoginRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientLoginRequest";
  }
  protected:
  explicit ClientLoginRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:game.client.ClientLoginRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// -------------------------------------------------------------------

class ClientLoginResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.client.ClientLoginResponse) */ {
 public:
  inline ClientLoginResponse() : ClientLoginResponse(nullptr) {}
  ~ClientLoginResponse() override;
  explicit constexpr ClientLoginResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientLoginResponse(const ClientLoginResponse& from);
  ClientLoginResponse(ClientLoginResponse&& from) noexcept
    : ClientLoginResponse() {
    *this = ::std::move(from);
  }

  inline ClientLoginResponse& operator=(const ClientLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientLoginResponse& operator=(ClientLoginResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientLoginResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientLoginResponse* internal_default_instance() {
    return reinterpret_cast<const ClientLoginResponse*>(
               &_ClientLoginResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ClientLoginResponse& a, ClientLoginResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientLoginResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientLoginResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientLoginResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientLoginResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientLoginResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientLoginResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientLoginResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientLoginResponse";
  }
  protected:
  explicit ClientLoginResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 2,
    kErrcodeFieldNumber = 1,
    kUserIdFieldNumber = 3,
  };
  // string errmsg = 2;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int32 errcode = 1;
  void clear_errcode();
  int32_t errcode() const;
  void set_errcode(int32_t value);
  private:
  int32_t _internal_errcode() const;
  void _internal_set_errcode(int32_t value);
  public:

  // int32 user_id = 3;
  void clear_user_id();
  int32_t user_id() const;
  void set_user_id(int32_t value);
  private:
  int32_t _internal_user_id() const;
  void _internal_set_user_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.client.ClientLoginResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  int32_t errcode_;
  int32_t user_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// -------------------------------------------------------------------

class ClientJoinMatchRequest final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:game.client.ClientJoinMatchRequest) */ {
 public:
  inline ClientJoinMatchRequest() : ClientJoinMatchRequest(nullptr) {}
  explicit constexpr ClientJoinMatchRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientJoinMatchRequest(const ClientJoinMatchRequest& from);
  ClientJoinMatchRequest(ClientJoinMatchRequest&& from) noexcept
    : ClientJoinMatchRequest() {
    *this = ::std::move(from);
  }

  inline ClientJoinMatchRequest& operator=(const ClientJoinMatchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientJoinMatchRequest& operator=(ClientJoinMatchRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientJoinMatchRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientJoinMatchRequest* internal_default_instance() {
    return reinterpret_cast<const ClientJoinMatchRequest*>(
               &_ClientJoinMatchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ClientJoinMatchRequest& a, ClientJoinMatchRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientJoinMatchRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientJoinMatchRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientJoinMatchRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientJoinMatchRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ClientJoinMatchRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ClientJoinMatchRequest& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientJoinMatchRequest";
  }
  protected:
  explicit ClientJoinMatchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:game.client.ClientJoinMatchRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// -------------------------------------------------------------------

class ClientJoinMatchResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.client.ClientJoinMatchResponse) */ {
 public:
  inline ClientJoinMatchResponse() : ClientJoinMatchResponse(nullptr) {}
  ~ClientJoinMatchResponse() override;
  explicit constexpr ClientJoinMatchResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientJoinMatchResponse(const ClientJoinMatchResponse& from);
  ClientJoinMatchResponse(ClientJoinMatchResponse&& from) noexcept
    : ClientJoinMatchResponse() {
    *this = ::std::move(from);
  }

  inline ClientJoinMatchResponse& operator=(const ClientJoinMatchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientJoinMatchResponse& operator=(ClientJoinMatchResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientJoinMatchResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientJoinMatchResponse* internal_default_instance() {
    return reinterpret_cast<const ClientJoinMatchResponse*>(
               &_ClientJoinMatchResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ClientJoinMatchResponse& a, ClientJoinMatchResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientJoinMatchResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientJoinMatchResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientJoinMatchResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientJoinMatchResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientJoinMatchResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientJoinMatchResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientJoinMatchResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientJoinMatchResponse";
  }
  protected:
  explicit ClientJoinMatchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 2,
    kErrcodeFieldNumber = 1,
  };
  // string errmsg = 2;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int32 errcode = 1;
  void clear_errcode();
  int32_t errcode() const;
  void set_errcode(int32_t value);
  private:
  int32_t _internal_errcode() const;
  void _internal_set_errcode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.client.ClientJoinMatchResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  int32_t errcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// -------------------------------------------------------------------

class ClientMatchSuccessPush final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.client.ClientMatchSuccessPush) */ {
 public:
  inline ClientMatchSuccessPush() : ClientMatchSuccessPush(nullptr) {}
  ~ClientMatchSuccessPush() override;
  explicit constexpr ClientMatchSuccessPush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientMatchSuccessPush(const ClientMatchSuccessPush& from);
  ClientMatchSuccessPush(ClientMatchSuccessPush&& from) noexcept
    : ClientMatchSuccessPush() {
    *this = ::std::move(from);
  }

  inline ClientMatchSuccessPush& operator=(const ClientMatchSuccessPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientMatchSuccessPush& operator=(ClientMatchSuccessPush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientMatchSuccessPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientMatchSuccessPush* internal_default_instance() {
    return reinterpret_cast<const ClientMatchSuccessPush*>(
               &_ClientMatchSuccessPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ClientMatchSuccessPush& a, ClientMatchSuccessPush& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientMatchSuccessPush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientMatchSuccessPush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientMatchSuccessPush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientMatchSuccessPush>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientMatchSuccessPush& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientMatchSuccessPush& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientMatchSuccessPush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientMatchSuccessPush";
  }
  protected:
  explicit ClientMatchSuccessPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBattleServerIpFieldNumber = 1,
    kBattleServerPortFieldNumber = 2,
  };
  // string battle_server_ip = 1;
  void clear_battle_server_ip();
  const std::string& battle_server_ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_battle_server_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_battle_server_ip();
  PROTOBUF_NODISCARD std::string* release_battle_server_ip();
  void set_allocated_battle_server_ip(std::string* battle_server_ip);
  private:
  const std::string& _internal_battle_server_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_battle_server_ip(const std::string& value);
  std::string* _internal_mutable_battle_server_ip();
  public:

  // int32 battle_server_port = 2;
  void clear_battle_server_port();
  int32_t battle_server_port() const;
  void set_battle_server_port(int32_t value);
  private:
  int32_t _internal_battle_server_port() const;
  void _internal_set_battle_server_port(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.client.ClientMatchSuccessPush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr battle_server_ip_;
  int32_t battle_server_port_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// -------------------------------------------------------------------

class ClientChatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.client.ClientChatRequest) */ {
 public:
  inline ClientChatRequest() : ClientChatRequest(nullptr) {}
  ~ClientChatRequest() override;
  explicit constexpr ClientChatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientChatRequest(const ClientChatRequest& from);
  ClientChatRequest(ClientChatRequest&& from) noexcept
    : ClientChatRequest() {
    *this = ::std::move(from);
  }

  inline ClientChatRequest& operator=(const ClientChatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientChatRequest& operator=(ClientChatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientChatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientChatRequest* internal_default_instance() {
    return reinterpret_cast<const ClientChatRequest*>(
               &_ClientChatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ClientChatRequest& a, ClientChatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientChatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientChatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientChatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientChatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientChatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientChatRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientChatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientChatRequest";
  }
  protected:
  explicit ClientChatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 3,
    kTargetIdFieldNumber = 1,
    kChatTypeFieldNumber = 2,
  };
  // string content = 3;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // int32 target_id = 1;
  void clear_target_id();
  int32_t target_id() const;
  void set_target_id(int32_t value);
  private:
  int32_t _internal_target_id() const;
  void _internal_set_target_id(int32_t value);
  public:

  // int32 chat_type = 2;
  void clear_chat_type();
  int32_t chat_type() const;
  void set_chat_type(int32_t value);
  private:
  int32_t _internal_chat_type() const;
  void _internal_set_chat_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.client.ClientChatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  int32_t target_id_;
  int32_t chat_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// -------------------------------------------------------------------

class ClientChatResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.client.ClientChatResponse) */ {
 public:
  inline ClientChatResponse() : ClientChatResponse(nullptr) {}
  ~ClientChatResponse() override;
  explicit constexpr ClientChatResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientChatResponse(const ClientChatResponse& from);
  ClientChatResponse(ClientChatResponse&& from) noexcept
    : ClientChatResponse() {
    *this = ::std::move(from);
  }

  inline ClientChatResponse& operator=(const ClientChatResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientChatResponse& operator=(ClientChatResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientChatResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientChatResponse* internal_default_instance() {
    return reinterpret_cast<const ClientChatResponse*>(
               &_ClientChatResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(ClientChatResponse& a, ClientChatResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientChatResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientChatResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientChatResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientChatResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientChatResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientChatResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientChatResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientChatResponse";
  }
  protected:
  explicit ClientChatResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 2,
    kErrcodeFieldNumber = 1,
  };
  // string errmsg = 2;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int32 errcode = 1;
  void clear_errcode();
  int32_t errcode() const;
  void set_errcode(int32_t value);
  private:
  int32_t _internal_errcode() const;
  void _internal_set_errcode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.client.ClientChatResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  int32_t errcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// -------------------------------------------------------------------

class ClientChatPush final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game.client.ClientChatPush) */ {
 public:
  inline ClientChatPush() : ClientChatPush(nullptr) {}
  ~ClientChatPush() override;
  explicit constexpr ClientChatPush(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientChatPush(const ClientChatPush& from);
  ClientChatPush(ClientChatPush&& from) noexcept
    : ClientChatPush() {
    *this = ::std::move(from);
  }

  inline ClientChatPush& operator=(const ClientChatPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientChatPush& operator=(ClientChatPush&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientChatPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClientChatPush* internal_default_instance() {
    return reinterpret_cast<const ClientChatPush*>(
               &_ClientChatPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(ClientChatPush& a, ClientChatPush& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientChatPush* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientChatPush* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientChatPush* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientChatPush>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientChatPush& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ClientChatPush& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientChatPush* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game.client.ClientChatPush";
  }
  protected:
  explicit ClientChatPush(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 3,
    kSenderIdFieldNumber = 1,
    kChatTypeFieldNumber = 2,
  };
  // string content = 3;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // int32 sender_id = 1;
  void clear_sender_id();
  int32_t sender_id() const;
  void set_sender_id(int32_t value);
  private:
  int32_t _internal_sender_id() const;
  void _internal_set_sender_id(int32_t value);
  public:

  // int32 chat_type = 2;
  void clear_chat_type();
  int32_t chat_type() const;
  void set_chat_type(int32_t value);
  private:
  int32_t _internal_chat_type() const;
  void _internal_set_chat_type(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game.client.ClientChatPush)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  int32_t sender_id_;
  int32_t chat_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_client_5fgateway_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientLoginRequest

// string username = 1;
inline void ClientLoginRequest::clear_username() {
  username_.ClearToEmpty();
}
inline const std::string& ClientLoginRequest::username() const {
  // @@protoc_insertion_point(field_get:game.client.ClientLoginRequest.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientLoginRequest::set_username(ArgT0&& arg0, ArgT... args) {
 
 username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientLoginRequest.username)
}
inline std::string* ClientLoginRequest::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:game.client.ClientLoginRequest.username)
  return _s;
}
inline const std::string& ClientLoginRequest::_internal_username() const {
  return username_.Get();
}
inline void ClientLoginRequest::_internal_set_username(const std::string& value) {
  
  username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientLoginRequest::_internal_mutable_username() {
  
  return username_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientLoginRequest::release_username() {
  // @@protoc_insertion_point(field_release:game.client.ClientLoginRequest.username)
  return username_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientLoginRequest::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  username_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (username_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    username_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientLoginRequest.username)
}

// string password = 2;
inline void ClientLoginRequest::clear_password() {
  password_.ClearToEmpty();
}
inline const std::string& ClientLoginRequest::password() const {
  // @@protoc_insertion_point(field_get:game.client.ClientLoginRequest.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientLoginRequest::set_password(ArgT0&& arg0, ArgT... args) {
 
 password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientLoginRequest.password)
}
inline std::string* ClientLoginRequest::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:game.client.ClientLoginRequest.password)
  return _s;
}
inline const std::string& ClientLoginRequest::_internal_password() const {
  return password_.Get();
}
inline void ClientLoginRequest::_internal_set_password(const std::string& value) {
  
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientLoginRequest::_internal_mutable_password() {
  
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientLoginRequest::release_password() {
  // @@protoc_insertion_point(field_release:game.client.ClientLoginRequest.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientLoginRequest::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientLoginRequest.password)
}

// -------------------------------------------------------------------

// ClientLoginResponse

// int32 errcode = 1;
inline void ClientLoginResponse::clear_errcode() {
  errcode_ = 0;
}
inline int32_t ClientLoginResponse::_internal_errcode() const {
  return errcode_;
}
inline int32_t ClientLoginResponse::errcode() const {
  // @@protoc_insertion_point(field_get:game.client.ClientLoginResponse.errcode)
  return _internal_errcode();
}
inline void ClientLoginResponse::_internal_set_errcode(int32_t value) {
  
  errcode_ = value;
}
inline void ClientLoginResponse::set_errcode(int32_t value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:game.client.ClientLoginResponse.errcode)
}

// string errmsg = 2;
inline void ClientLoginResponse::clear_errmsg() {
  errmsg_.ClearToEmpty();
}
inline const std::string& ClientLoginResponse::errmsg() const {
  // @@protoc_insertion_point(field_get:game.client.ClientLoginResponse.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientLoginResponse::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientLoginResponse.errmsg)
}
inline std::string* ClientLoginResponse::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:game.client.ClientLoginResponse.errmsg)
  return _s;
}
inline const std::string& ClientLoginResponse::_internal_errmsg() const {
  return errmsg_.Get();
}
inline void ClientLoginResponse::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientLoginResponse::_internal_mutable_errmsg() {
  
  return errmsg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientLoginResponse::release_errmsg() {
  // @@protoc_insertion_point(field_release:game.client.ClientLoginResponse.errmsg)
  return errmsg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientLoginResponse::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (errmsg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientLoginResponse.errmsg)
}

// int32 user_id = 3;
inline void ClientLoginResponse::clear_user_id() {
  user_id_ = 0;
}
inline int32_t ClientLoginResponse::_internal_user_id() const {
  return user_id_;
}
inline int32_t ClientLoginResponse::user_id() const {
  // @@protoc_insertion_point(field_get:game.client.ClientLoginResponse.user_id)
  return _internal_user_id();
}
inline void ClientLoginResponse::_internal_set_user_id(int32_t value) {
  
  user_id_ = value;
}
inline void ClientLoginResponse::set_user_id(int32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:game.client.ClientLoginResponse.user_id)
}

// -------------------------------------------------------------------

// ClientJoinMatchRequest

// -------------------------------------------------------------------

// ClientJoinMatchResponse

// int32 errcode = 1;
inline void ClientJoinMatchResponse::clear_errcode() {
  errcode_ = 0;
}
inline int32_t ClientJoinMatchResponse::_internal_errcode() const {
  return errcode_;
}
inline int32_t ClientJoinMatchResponse::errcode() const {
  // @@protoc_insertion_point(field_get:game.client.ClientJoinMatchResponse.errcode)
  return _internal_errcode();
}
inline void ClientJoinMatchResponse::_internal_set_errcode(int32_t value) {
  
  errcode_ = value;
}
inline void ClientJoinMatchResponse::set_errcode(int32_t value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:game.client.ClientJoinMatchResponse.errcode)
}

// string errmsg = 2;
inline void ClientJoinMatchResponse::clear_errmsg() {
  errmsg_.ClearToEmpty();
}
inline const std::string& ClientJoinMatchResponse::errmsg() const {
  // @@protoc_insertion_point(field_get:game.client.ClientJoinMatchResponse.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientJoinMatchResponse::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientJoinMatchResponse.errmsg)
}
inline std::string* ClientJoinMatchResponse::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:game.client.ClientJoinMatchResponse.errmsg)
  return _s;
}
inline const std::string& ClientJoinMatchResponse::_internal_errmsg() const {
  return errmsg_.Get();
}
inline void ClientJoinMatchResponse::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientJoinMatchResponse::_internal_mutable_errmsg() {
  
  return errmsg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientJoinMatchResponse::release_errmsg() {
  // @@protoc_insertion_point(field_release:game.client.ClientJoinMatchResponse.errmsg)
  return errmsg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientJoinMatchResponse::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (errmsg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientJoinMatchResponse.errmsg)
}

// -------------------------------------------------------------------

// ClientMatchSuccessPush

// string battle_server_ip = 1;
inline void ClientMatchSuccessPush::clear_battle_server_ip() {
  battle_server_ip_.ClearToEmpty();
}
inline const std::string& ClientMatchSuccessPush::battle_server_ip() const {
  // @@protoc_insertion_point(field_get:game.client.ClientMatchSuccessPush.battle_server_ip)
  return _internal_battle_server_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientMatchSuccessPush::set_battle_server_ip(ArgT0&& arg0, ArgT... args) {
 
 battle_server_ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientMatchSuccessPush.battle_server_ip)
}
inline std::string* ClientMatchSuccessPush::mutable_battle_server_ip() {
  std::string* _s = _internal_mutable_battle_server_ip();
  // @@protoc_insertion_point(field_mutable:game.client.ClientMatchSuccessPush.battle_server_ip)
  return _s;
}
inline const std::string& ClientMatchSuccessPush::_internal_battle_server_ip() const {
  return battle_server_ip_.Get();
}
inline void ClientMatchSuccessPush::_internal_set_battle_server_ip(const std::string& value) {
  
  battle_server_ip_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientMatchSuccessPush::_internal_mutable_battle_server_ip() {
  
  return battle_server_ip_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientMatchSuccessPush::release_battle_server_ip() {
  // @@protoc_insertion_point(field_release:game.client.ClientMatchSuccessPush.battle_server_ip)
  return battle_server_ip_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientMatchSuccessPush::set_allocated_battle_server_ip(std::string* battle_server_ip) {
  if (battle_server_ip != nullptr) {
    
  } else {
    
  }
  battle_server_ip_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), battle_server_ip,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (battle_server_ip_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    battle_server_ip_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientMatchSuccessPush.battle_server_ip)
}

// int32 battle_server_port = 2;
inline void ClientMatchSuccessPush::clear_battle_server_port() {
  battle_server_port_ = 0;
}
inline int32_t ClientMatchSuccessPush::_internal_battle_server_port() const {
  return battle_server_port_;
}
inline int32_t ClientMatchSuccessPush::battle_server_port() const {
  // @@protoc_insertion_point(field_get:game.client.ClientMatchSuccessPush.battle_server_port)
  return _internal_battle_server_port();
}
inline void ClientMatchSuccessPush::_internal_set_battle_server_port(int32_t value) {
  
  battle_server_port_ = value;
}
inline void ClientMatchSuccessPush::set_battle_server_port(int32_t value) {
  _internal_set_battle_server_port(value);
  // @@protoc_insertion_point(field_set:game.client.ClientMatchSuccessPush.battle_server_port)
}

// -------------------------------------------------------------------

// ClientChatRequest

// int32 target_id = 1;
inline void ClientChatRequest::clear_target_id() {
  target_id_ = 0;
}
inline int32_t ClientChatRequest::_internal_target_id() const {
  return target_id_;
}
inline int32_t ClientChatRequest::target_id() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatRequest.target_id)
  return _internal_target_id();
}
inline void ClientChatRequest::_internal_set_target_id(int32_t value) {
  
  target_id_ = value;
}
inline void ClientChatRequest::set_target_id(int32_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:game.client.ClientChatRequest.target_id)
}

// int32 chat_type = 2;
inline void ClientChatRequest::clear_chat_type() {
  chat_type_ = 0;
}
inline int32_t ClientChatRequest::_internal_chat_type() const {
  return chat_type_;
}
inline int32_t ClientChatRequest::chat_type() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatRequest.chat_type)
  return _internal_chat_type();
}
inline void ClientChatRequest::_internal_set_chat_type(int32_t value) {
  
  chat_type_ = value;
}
inline void ClientChatRequest::set_chat_type(int32_t value) {
  _internal_set_chat_type(value);
  // @@protoc_insertion_point(field_set:game.client.ClientChatRequest.chat_type)
}

// string content = 3;
inline void ClientChatRequest::clear_content() {
  content_.ClearToEmpty();
}
inline const std::string& ClientChatRequest::content() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatRequest.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientChatRequest::set_content(ArgT0&& arg0, ArgT... args) {
 
 content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientChatRequest.content)
}
inline std::string* ClientChatRequest::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:game.client.ClientChatRequest.content)
  return _s;
}
inline const std::string& ClientChatRequest::_internal_content() const {
  return content_.Get();
}
inline void ClientChatRequest::_internal_set_content(const std::string& value) {
  
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientChatRequest::_internal_mutable_content() {
  
  return content_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientChatRequest::release_content() {
  // @@protoc_insertion_point(field_release:game.client.ClientChatRequest.content)
  return content_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientChatRequest::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (content_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    content_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientChatRequest.content)
}

// -------------------------------------------------------------------

// ClientChatResponse

// int32 errcode = 1;
inline void ClientChatResponse::clear_errcode() {
  errcode_ = 0;
}
inline int32_t ClientChatResponse::_internal_errcode() const {
  return errcode_;
}
inline int32_t ClientChatResponse::errcode() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatResponse.errcode)
  return _internal_errcode();
}
inline void ClientChatResponse::_internal_set_errcode(int32_t value) {
  
  errcode_ = value;
}
inline void ClientChatResponse::set_errcode(int32_t value) {
  _internal_set_errcode(value);
  // @@protoc_insertion_point(field_set:game.client.ClientChatResponse.errcode)
}

// string errmsg = 2;
inline void ClientChatResponse::clear_errmsg() {
  errmsg_.ClearToEmpty();
}
inline const std::string& ClientChatResponse::errmsg() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatResponse.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientChatResponse::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientChatResponse.errmsg)
}
inline std::string* ClientChatResponse::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:game.client.ClientChatResponse.errmsg)
  return _s;
}
inline const std::string& ClientChatResponse::_internal_errmsg() const {
  return errmsg_.Get();
}
inline void ClientChatResponse::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientChatResponse::_internal_mutable_errmsg() {
  
  return errmsg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientChatResponse::release_errmsg() {
  // @@protoc_insertion_point(field_release:game.client.ClientChatResponse.errmsg)
  return errmsg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientChatResponse::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (errmsg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientChatResponse.errmsg)
}

// -------------------------------------------------------------------

// ClientChatPush

// int32 sender_id = 1;
inline void ClientChatPush::clear_sender_id() {
  sender_id_ = 0;
}
inline int32_t ClientChatPush::_internal_sender_id() const {
  return sender_id_;
}
inline int32_t ClientChatPush::sender_id() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatPush.sender_id)
  return _internal_sender_id();
}
inline void ClientChatPush::_internal_set_sender_id(int32_t value) {
  
  sender_id_ = value;
}
inline void ClientChatPush::set_sender_id(int32_t value) {
  _internal_set_sender_id(value);
  // @@protoc_insertion_point(field_set:game.client.ClientChatPush.sender_id)
}

// int32 chat_type = 2;
inline void ClientChatPush::clear_chat_type() {
  chat_type_ = 0;
}
inline int32_t ClientChatPush::_internal_chat_type() const {
  return chat_type_;
}
inline int32_t ClientChatPush::chat_type() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatPush.chat_type)
  return _internal_chat_type();
}
inline void ClientChatPush::_internal_set_chat_type(int32_t value) {
  
  chat_type_ = value;
}
inline void ClientChatPush::set_chat_type(int32_t value) {
  _internal_set_chat_type(value);
  // @@protoc_insertion_point(field_set:game.client.ClientChatPush.chat_type)
}

// string content = 3;
inline void ClientChatPush::clear_content() {
  content_.ClearToEmpty();
}
inline const std::string& ClientChatPush::content() const {
  // @@protoc_insertion_point(field_get:game.client.ClientChatPush.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientChatPush::set_content(ArgT0&& arg0, ArgT... args) {
 
 content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game.client.ClientChatPush.content)
}
inline std::string* ClientChatPush::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:game.client.ClientChatPush.content)
  return _s;
}
inline const std::string& ClientChatPush::_internal_content() const {
  return content_.Get();
}
inline void ClientChatPush::_internal_set_content(const std::string& value) {
  
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ClientChatPush::_internal_mutable_content() {
  
  return content_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ClientChatPush::release_content() {
  // @@protoc_insertion_point(field_release:game.client.ClientChatPush.content)
  return content_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ClientChatPush::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (content_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    content_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game.client.ClientChatPush.content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace client
}  // namespace game

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_client_5fgateway_2eproto
